# Generated by Django 3.2 on 2022-06-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ratings',
            new_name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
    ]
