# Generated by Django 3.2 on 2023-01-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklistapp', '0002_auto_20220603_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='booklistapp.publisher'),
            preserve_default=False,
        ),
    ]
